// packages/screen-recorder-react/src/App.tsx
import React from 'react'
import ScreenRecorder from './components/ScreenRecorder'
import Video from './components/Video'
import './App.css'

export default () => {

  const [recording, setRecording] = React.useState(false);

  const videoOptions: MediaTrackConstraints = {
    width: 1920,
    height: 1080,
    frameRate: 60,
  };

  const start = (startEvent: Function) => {
    startEvent();
    setRecording(true);
  };

  const recordingEnd = (url: string) => {
    setRecording(false);
    console.log(url);
    // to do sth for url
  }

  const startContent = (startEvent: Function) => !recording && <button onClick={() => start(startEvent)}>开始录屏</button>
  const endContent = (endEvent: Function) => recording && <button onClick={() => endEvent()}>结束录屏</button>
  const previewContent = (mediaStream: MediaStream) =>
    <Video
      muted
      autoPlay
      style={{ display: 'block' }}
      width={500}
      srcObject={mediaStream}
    />
  return (
    <>
      <h1>1. Simple use</h1>
      <ScreenRecorder
        preview
        onRecordingEnd={recordingEnd}
        startBtnText="🛫 开始"
        startBtnStyle={{ color: '#48bfa7' }}
        endBtnText="🛑 结束"
        endBtnStyle={{ color: 'red' }}
      />

      <hr style={{ margin: '50px 0' }} />

      <h1>2. Custom use</h1>
      <ScreenRecorder
        preview
        shortKey="Alt+Shift+R"
        videoOptions={videoOptions}
        onRecordingEnd={recordingEnd}
        startContent={startContent}
        endContent={endContent}
        previewContent={previewContent}
      />
    </>
  )
}

// packages/screen-recorder-vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import ScreenRecorderVue from "screen-recorder-vue";

const recording = ref(false);

const videoOptions: MediaTrackConstraints = {
  width: 1920,
  height: 1080,
  frameRate: 60,
};

const start = (startEvent: Function) => {
  startEvent();
  recording.value = true;
};

const recordingEnd = (url: string) => {
  recording.value = false;
  console.log(url);
  // to do sth for url
};
</script>

<template>
  <h1>1. Simple use</h1>
  <ScreenRecorderVue
    preview
    @recording-end="recordingEnd"
    start-btn-text="🛫 开始"
    start-btn-style="color: #48bfa7"
    end-btn-text="🛑 结束"
    end-btn-style="color: red;"
  />

  <hr style="margin: 50px 0" />

  <h1>2. Custom slots use</h1>
  <ScreenRecorderVue
    preview
    short-key="Alt+Shift+R"
    :video-options="videoOptions"
    @recording-end="recordingEnd"
  >
    <template v-slot:start="{ startEvent }">
      <button v-if="!recording" @click="start(startEvent)">开始录屏</button>
    </template>

    <template v-slot:end="{ endEvent }">
      <button v-if="recording" @click="endEvent">结束录屏</button>
    </template>

    <template v-slot:preview="{ mediaStream }">
      <div>
        <video muted autoplay width="500" :srcObject="mediaStream"></video>
      </div>
    </template>
  </ScreenRecorderVue>
</template>
<style scoped>
button {
  cursor: pointer;
  margin: 16px;
}
</style>
