// packages/screen-recorder-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = "screen-recorder-angular"

  recording = false

  videoOptions: MediaTrackConstraints = {
    width: 1920,
    height: 1080,
    frameRate: 60,
  };

  start = (startEvent: Function) => {
    startEvent();
    this.recording = true;
  };

  recordingEnd = ({ url }: { url: string }) => {
    console.log(url);
    // to do sth for url
  };

  customRecordingEnd = ({ url }: { url: string }) => {
    this.recording = false;
    console.log(url);
    // to do sth for url
  };
}

<h1>1. Simple use</h1>
<app-screen-recorder [preview]="true" (onRecordingEnd)="recordingEnd($event)" startBtnText="🛫 开始"
  startBtnStyle="color:#48bfa7" endBtnText="🛑 结束" endBtnStyle="color: red"></app-screen-recorder>

<hr style="margin: 50px 0" />

<h1>2. Custom slots use</h1>
<app-screen-recorder [preview]="true" shortKey="Alt+Shift+R" [videoOptions]="videoOptions"
  (onRecordingEnd)="customRecordingEnd($event)">
  <ng-template startContent let-startEvent="startEvent">
    <button *ngIf="!recording" (click)="start(startEvent)">开始录屏</button>
  </ng-template>
  <ng-template endContent let-endEvent="endEvent">
    <button *ngIf="recording" (click)="endEvent()">结束录屏</button>
  </ng-template>
  <ng-template previewContent let-mediaStream="mediaStream">
    <video muted autoplay width="500" style="display: block;" [srcObject]="mediaStream"></video>
  </ng-template>
</app-screen-recorder>

// packages/screen-recorder-react/src/App.tsx
import React from 'react'
import ScreenRecorder from './components/ScreenRecorder'
import Video from './components/Video'
import './App.css'

export default () => {

  const [recording, setRecording] = React.useState(false);

  const videoOptions: MediaTrackConstraints = {
    width: 1920,
    height: 1080,
    frameRate: 60,
  };

  const start = (startEvent: Function) => {
    startEvent();
    setRecording(true);
  };

  const recordingEnd = (url: string) => {
    console.log(url);
    // to do sth for url
  }

  const customRecordingEnd = (url: string) => {
    setRecording(false);
    console.log(url);
    // to do sth for url
  }

  const startContent = (startEvent: Function) => !recording && <button onClick={() => start(startEvent)}>开始录屏</button>
  const endContent = (endEvent: Function) => recording && <button onClick={() => endEvent()}>结束录屏</button>
  const previewContent = (mediaStream: MediaStream) =>
    <Video
      muted
      autoPlay
      style={{ display: 'block' }}
      width={500}
      srcObject={mediaStream}
    />
  return (
    <>
      <h1>1. Simple use</h1>
      <ScreenRecorder
        preview
        onRecordingEnd={recordingEnd}
        startBtnText="🛫 开始"
        startBtnStyle={{ color: '#48bfa7' }}
        endBtnText="🛑 结束"
        endBtnStyle={{ color: 'red' }}
      />

      <hr style={{ margin: '50px 0' }} />

      <h1>2. Custom use</h1>
      <ScreenRecorder
        preview
        shortKey="Alt+Shift+R"
        videoOptions={videoOptions}
        onRecordingEnd={customRecordingEnd}
        startContent={startContent}
        endContent={endContent}
        previewContent={previewContent}
      />
    </>
  )
}
